[package]
name = "array-queue"
description = "Fixed size bidirectional queues based on arrays"
version = "0.3.3"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
license = "MIT"

[dependencies]
arrayvec = "0.4"
